name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 코드를 푸시할 때마다 작업이 시작

jobs:
  build_and_deploy:
    # 이 워크플로우는 최신 우분투 환경에서 실행
    runs-on: ubuntu-latest

    steps:
      # 저장소 코드 체크아웃
      - uses: actions/checkout@v3
      
      # Flutter 환경 설정
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 안정화 버전 사용
          cache: true
      
      # 필요한 패키지 다운로드
      - run: flutter pub get
      
      # Flutter Web 빌드
      - run: flutter build web --base-href /Guitar_Helper/ 
      
      # 5. 빌드된 결과물(build/web)을 gh-pages 브랜치에 배포
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages # 배포할 대상 브랜치